---
- name: "Gather Facts"
  hosts: vsrx
  connection: local 
  roles:
    - Juniper.junos 
  gather_facts: no 

  tasks:
  - name: Gathering info from devices
    junos_get_facts: 
      user=root
      passwd=Juniper
      port={{ ncssh_port }}
      host={{ ip_addr }}
    register: junos

  - name: Device name
    debug: msg={{ junos.facts.hostname }}

  - name: OS Version
    debug: msg={{ junos.facts.version }}

  - name: Device Model
    debug: msg={{ junos.facts.model }}
    
  - name: Serial-number
    debug: msg={{ junos.facts.serialnumber }}
